name:                streamfind
version:             0.1.8.0

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on Github at <https://github.com/githubuser/bal#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- wreq
- text
- vector
- lens
- unordered-containers
- aeson
- http-types
- feed
- sqlite-simple
- cryptonite
- memory
- time
- http-client
- regex-posix
- optparse-applicative
- split

library:
  source-dirs: src

executables:
  streamfind:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamfind

extra-source-files:
- README.md
- examples/*.hs
